name: CHANGELOG check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check for updates
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed CHANGELOG
        id: changelog-diff
        uses: tj-actions/changed-files@v44
        with:
          files: CHANGELOG.md

      - name: Fail if changelog not updated
        if: steps.changelog-diff.outputs.any_changed == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('CHANGELOG.md has not been updated')
